### PR TITLE
Validate campaign urls to ensure they are valid URI

### LINKED ISSUE #809: URI::InvalidURIError: URI must be ascii only "\u200Bhttps://calibreapp.com/?utm_source=codefund&utm_campaign=makethewebfast"
View details in Rollbar: [https://rollbar.com/codefund/codefund/items/358/](https://rollbar.com/codefund/codefund/items/358/)

```

URI::InvalidURIError: URI must be ascii only "\u200Bhttps://calibreapp.com/?utm_source=codefund&utm_campaign=makethewebfast"
  File "/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/uri/rfc3986_parser.rb", line 21, in split
  File "/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/uri/rfc3986_parser.rb", line 73, in parse
  File "/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/uri/common.rb", line 234, in parse
  File "/app/app/controllers/advertisement_clicks_controller.rb", line 9, in show
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_controller/metal/basic_implicit_render.rb", line 6, in send_action
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/abstract_controller/base.rb", line 196, in process_action
  File "/app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.6.2/lib/scout_apm/instruments/action_controller_rails_3_rails4.rb", line 73, in process_action
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_controller/metal/rendering.rb", line 30, in process_action
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/abstract_controller/callbacks.rb", line 42, in block in process_action
  File "/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb", line 135, in run_callbacks
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/abstract_controller/callbacks.rb", line 41, in process_action
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_controller/metal/rescue.rb", line 22, in process_action
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_controller/metal/instrumentation.rb", line 33, in block in process_action
  File "/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/notifications.rb", line 180, in block in instrument
  File "/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/notifications/instrumenter.rb", line 24, in instrument
  File "/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/notifications.rb", line 180, in instrument
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_controller/metal/instrumentation.rb", line 32, in process_action
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_controller/metal/params_wrapper.rb", line 245, in process_action
  File "/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.1/lib/active_record/railties/controller_runtime.rb", line 27, in process_action
  File "/app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.6.2/lib/scout_apm/instruments/action_controller_rails_3_rails4.rb", line 86, in process_action
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/abstract_controller/base.rb", line 136, in process
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionview-6.0.1/lib/action_view/rendering.rb", line 39, in process
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_controller/metal.rb", line 191, in dispatch
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_controller/metal.rb", line 252, in dispatch
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_dispatch/routing/route_set.rb", line 51, in dispatch
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_dispatch/routing/route_set.rb", line 33, in serve
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_dispatch/journey/router.rb", line 49, in block in serve
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_dispatch/journey/router.rb", line 32, in each
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_dispatch/journey/router.rb", line 32, in serve
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_dispatch/routing/route_set.rb", line 837, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.6.2/lib/scout_apm/instruments/rails_router.rb", line 29, in call_with_scout_instruments
  File "/app/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb", line 192, in call!
  File "/app/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb", line 169, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.6.2/lib/scout_apm/middleware.rb", line 17, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/rack-attack-6.1.0/lib/rack/attack.rb", line 158, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb", line 36, in block in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb", line 34, in catch
  File "/app/vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb", line 34, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/tempfile_reaper.rb", line 15, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/etag.rb", line 25, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/conditional_get.rb", line 25, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/head.rb", line 12, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_dispatch/http/content_security_policy.rb", line 18, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb", line 232, in context
  File "/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb", line 226, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_dispatch/middleware/cookies.rb", line 648, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_dispatch/middleware/callbacks.rb", line 27, in block in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/callbacks.rb", line 101, in run_callbacks
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_dispatch/middleware/callbacks.rb", line 26, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_dispatch/middleware/actionable_exceptions.rb", line 17, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/airbrake-9.5.0/lib/airbrake/rack/middleware.rb", line 32, in call!
  File "/app/vendor/bundle/ruby/2.6.0/gems/airbrake-9.5.0/lib/airbrake/rack/middleware.rb", line 21, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.22.1/lib/rollbar/middleware/rails/rollbar.rb", line 25, in block in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.22.1/lib/rollbar.rb", line 145, in scoped
  File "/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.22.1/lib/rollbar/middleware/rails/rollbar.rb", line 22, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.1/lib/action_dispatch/middleware/debug_exceptions.rb", line 32, in call
  File "/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.22.1/lib/rollbar/middleware/rails/show_exceptions.rb", line 22, in call_with_rollbar
  File "/app/vendor

### PR DESCRIPTION
**Pull request by hopsoft**
## Description

Parse url param to ensure a valid URL

Fixes #809 

### General

- [x] My code follows the style guidelines of this project & the tests are passing
- [x] I have performed a self-review of my own code
- [x] I have updated DB schema annotations or I have not made any DB schema changes

### CodeFund Core Team

- [ ] I have added the appropriate milestone if applicable
- [x] I have requested a review from another developer(s)

### CODE REVIEW

File: app/models/campaign.rb [hunk 1]
```diff
@@ -412,17 +412,10 @@ def sanitize_assigned_property_ids
...
-    case uri
-    when URI::HTTP, URI::HTTPS
-      response = Typhoeus.get(uri.to_s, followlocation: true)
-      errors[:url] << "is invalid" unless response.success?
-    else errors[:url] << "is invalid"
-    end
+    self.url = url.to_s.strip
+    URI.parse(url)
+  rescue
+    errors[:url] << "is invalid"
```
Comment (andrewmcodes) [inline app/models/campaign.rb]: Any reason you are shoveling this in? I am not seeing why this would be an array..
